name: Melon Ticket Bot

on:
  schedule:
    - cron: '*/5 * * * *'  # 每5分钟执行一次
  workflow_dispatch:       # 手动触发支持

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Run ticket bot
        env:
          MELON_ID: ${{ secrets.2388426228@qq.com }}
          MELON_PW: ${{ secrets.yjh951004 }}
          CONCERT_ID: '211358'
        run: node src/index.js

